name: sample_time_zone_flutter
description: Implementation time zone in Flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  timezone: any
  dio: any
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_annotation: any
  json_serializable: any
  build_runner: any

flutter:
  uses-material-design: true
